services:
  - type: web
    name: party-hitz-server
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
